[build]
  publish = "dist"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "20"

# Domain redirect - always redirect to aibek.me
[[redirects]]
  from = "https://aibekz.com/*"
  to = "https://aibek.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.aibekz.com/*"
  to = "https://aibek.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.aibek.me/*"
  to = "https://aibek.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/api/*"
  to = "https://aibekz.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"
